# Guy Bruneau
# Version 1.0
# Date: 25 Jan 2025

# This file must have the following permissions and user associated to it:
# Metricbeat is used first of all to load the metricbeat templates into Kibana
# The template can be used to ingest data from a cloud sensor
# by pointing the logs to logstash
#
# sudo chown -R root:root ~/DShield-SIEM/metricbeat/*
# sudo chmod 644 ~/DShield-SIEM/metricbeat/metricbeat.yml
#
# sudo docker exec -ti metricbeat bash
# ./metricbeat setup -e 


#==========================  Modules configuration ============================

metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 10s
#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false


# =================================== Kibana ===================================
setup.kibana:

  host: "https://kibana:5601"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
    certificate: "/usr/share/metricbeat/certs/kibana/kibana.crt"
    key: "/usr/share/metricbeat/certs/kibana/kibana.key"
    verification_mode: "certificate"


# =============================== Elasticsearch ===================================
#
output.elasticsearch:
  hosts: ["es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
    certificate: "/usr/share/metricbeat/certs/metricbeat/metricbeat.crt"
    key: "/usr/share/metricbeat/certs/metricbeat/metricbeat.key"
    verification_mode: "certificate"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#============================== X-Pack Monitoring ===============================
# metricbeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
monitoring.enabled: true


