# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.15/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://metricbeat:5066","filebeat:5067","filebeat01:5068"]
  protocol: "https"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
    verification_mode: "certificate"

