# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.15/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://metricbeat:5066","filebeat:5067"]
  #username: "user"
  #password: "secret"

