# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.15/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
    certificate: "/usr/share/metricbeat/certs/metricbeat/metricbeat.crt"
    key: "/usr/share/metricbeat/certs/metricbeat/metricbeat.key"
    verification_mode: "certificate"


